### ISSUE TITLE
Buzzer Details

### ISSUE THREAD

**Issue by Noah-Burns** [Ajusa/crackbowl#5]
- Press space to buzz, no other way to buzz (like clicking anything, unless you code a specific "buzz" button)
- Once buzzed, you can't "unbuzz"
- Five seconds to type after buzzing, three (?) to buzz after last word is read

**Comment by ajusa** [comment]
First one is done, I added a buzz button
Second one is also done. Working on the third right now

**Comment by ajusa** [comment]
I don't think it'll be easy to remove the buzz on clicking on the input, so I will probably leave that their. Timer is done, so closing this issue
